### ISSUE TITLE
(注意点) POファイルと、OmegaTの文節の切り方が異なる

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#2]
POファイルには、複数文節が一つの翻訳単位としてふくまれることがありますが、OmegaTでは、文の単位で処理されるため、既存の翻訳成果が反映されないことがあります。
そのため、翻訳の進捗が少なくみえていますので、このケースの修正は、率先して実施してください。
TMフォルダにインポートしたTMXファイルの生成時に、文節への変換を処理することで、この問題を改善することができる可能性があります。

**Comment by sanak** [comment]
posegmentの方を、tmフォルダ内にのみ効かせる。
- https://github.com/translate/translate
- https://github.com/translate/translate/issues/3280
- http://docs.translatehouse.org/projects/translate-toolkit/en/1.10.0/commands/posegment.html

**Comment by sanak** [comment]
あまり書き方が良くないとは思いますが、取り急ぎ、下記のコミットにて分節区切りに対応しました。
commit diff:https://github.com/OSGeo-jp/OSGeoLive-doc-omegat/commit/fca03f46c8bc5e8f54e9394c7f512c16677192be
