### ISSUE TITLE
[改善要望] プロジェクト用語変更「翻訳辞書」

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#28]
**改善要望は何らかの問題に関連していますか？ 説明をお願いします。**
Issueテンプレートで、「翻訳辞書」の用語を使用しているが、「英和辞書」や「オンライン辞書」とまぎわらしい。

**望ましい解決策についての説明**
"glossary"の訳語としては、「用語集」か、「対訳用語集」が定訳の認識です。

**検討した代替案についての説明**
英和辞書では、glossaryにつぎの用語を提案しています。 用語集、用語［語彙］解説 用語辞典、語彙集、

**Comment by sanak** [comment]
@miurahr 上記のご指摘、ありがとうございます。:bow:
Transifexの方でも用語集と翻訳しているようでしたので、用語集に変更します。
https://www.transifex.com/osgeo/osgeolive/glossary/ja/

今晩中目処で、ラベルとISSUES TEMPLATESの方を修正するようにします。

**Comment by sanak** [comment]
@miurahr こちら、 #36 のPRと、https://github.com/OSGeo-jp/OSGeoLive-doc-omegat/commit/d642777f57275bd548a9f4be3041cec81393e0eb のコミットで対応しましたので、クローズします。
