### ISSUE TITLE
OmegaTでの訳文生成時に、原文と訳文が同じ場合、訳文が空になる問題の対応

### ISSUE THREAD

**Issue by sanak** [OSGeo-jp/OSGeoLive-doc-omegat#3]
OSGeoLive-doc側でビルド時に生成される日本語HTMLは同じになりますが、Transifex上で100%にならなくなり、OSGeoLive-docでも翻訳率100%のもののみ `tx pull` で適用される形になりますので、 `target` フォルダについてもGit管理下に含め、既存ツール？や自作Pythonスクリプトなどで `source` / `target` フォルダ間の訳文比較を行い、原文と訳文が同じで、 `target` 側で空白となっている場合は埋める処理を行う方向で検討しています。

- 既存ツールの場合:
   - gettext系 or translate or i18ndude ?
- 自作Pythonスクリプトの場合:
   - `polib` などのライブラリを検討: https://stackoverflow.com/questions/9580449/parsing-gettext-po-files-with-python/9998895#9998895

**Comment by miurahr** [comment]
PO Fileのフィルター設定の

> **PO files**
>  * Allow blank translations in the target file:
>  If selected, when a segment in a PO file (which may be a whole paragraph) is not translated, the translation will be empty in the target file. Technically speaking, the msgstr segment in the PO target file, if created, will be left empty. As this is the standard behaviour for PO files, it is selected by default. If the option is off, the source text will be copied to the target segment.
>
>* Skip PO header
>
>   The PO header will be skipped and left unchanged if this option is checked.

https://omegat.sourceforge.io/manual-standard/en/windows.and.dialogs.html#dialogs.preferences

を使用して、かつ `omegat/filters.xml`をプロジェクトで共有する。

https://omegat.sourceforge.io/manual-standard/en/project.folder.html#d0e4690

対応になりそうです。

**Comment by sanak** [comment]
@miurahr 上記、了解しました。情報ありがとうございます。
今晩遅くになるかもしれませんが、上記について動作を確認の上、pushします。

**Comment by sanak** [comment]
昨晩はダウンしてしまいました...。
下記のサイトも参考に、プロジェクトのフィルタ設定を有効にし、動作確認の上、空分節の許可を原文の方にチェックを入れたものを、先ほどmasterブランチにpushしました。
参考サイト: https://momdo.hatenablog.jp/entry/20190313/1552485226
1. ![omegat_filter1](https://user-images.githubusercontent.com/629923/100153909-29973d80-2ee8-11eb-8a93-bc5b2561dc1d.png)
2. ![omegat_filter2](https://user-images.githubusercontent.com/629923/100153971-403d9480-2ee8-11eb-9a74-e115eefdb8dd.png)
3. ![omegat_filter3](https://user-images.githubusercontent.com/629923/100153977-4469b200-2ee8-11eb-9ad3-0ef3b36dd763.png)
4. ![omegat_filter4](https://user-images.githubusercontent.com/629923/100153987-47fd3900-2ee8-11eb-9277-74294e9493ed.png)

**Comment by miurahr** [comment]
コミットで
```
        <option name="disallowBlank" value="false"/>
￼        <option name="disallowEditingBlankSegment" value="true"/>
```
になっていますが、

```
        <option name="disallowBlank" value="true"/>
        <option name="disallowEditingBlankSegment" value="false"/>
```
なんではないかと、おもうんですが。
こうすると、翻訳が原文とおなじ場合に、訳文のフィールドに原文がはいった状態で出力されます。

**Comment by sanak** [comment]
はい、最初に下記で試してみたんですが、 `source/overview/cesium_overview.po` のみで動作確認したところ、出力の方が空になってしまい、
```
        <option name="disallowBlank" value="true"/>
        <option name="disallowEditingBlankSegment" value="false"/>
```
以下に切り替えると上手く動作しました。
```
        <option name="disallowBlank" value="false"/>
￼        <option name="disallowEditingBlankSegment" value="true"/>
```

ただ、今、全体チェック中ですが、 `contact.po` の方で原文で翻訳されていない(=`msgstr:""`)状態でも、訳文で英語表記されてましたので、やはり間違っているかもしれません...。

一旦、ご指摘の内容に戻しておき、自作Pythonスクリプトの線も引き続き検討するようにします。(対応は今週末になると思います。)

**Comment by sanak** [comment]
こちらの問題ですが、どうも別の設定が必要のようでした。
https://sourceforge.net/p/omegat-jp/wiki/Team_Project_howto/#_16
> [設定]-[翻訳入力行...]-[原文と同じ訳文を許可] に、チェックを入れておいてください。
> 
> もしチェックが外れていると、原文と同じ訳文が設定されている分節を離れる （アクティブにしてから別の分節へ移動する）だけで、 訳文が削除されてしまいます。
> 
> この設定は今のところプロジェクト専用の設定が存在しないため、 作業者の環境によって設定値が異なる可能性があります。

後ほど、#6 の方でREADME.mdに設定手順として追記するようにします。

**Comment by sanak** [comment]
対応済みのため、クローズします。
