### ISSUE TITLE
[日本語訳文] Documentationの訳文のゆれ

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#31]
**問題の説明**
文書、ドキュメント、ドキュメンテーション の3種類存在している。

文書、文書化 の対か、    ドキュメント、ドキュメンテーション  の対であるべき。

**修正案についての説明**

文書、文書化  に統一する

関連： #29

**Comment by sanak** [comment]
文書は、過去のOSGeoLive翻訳時に、 `Quickstart documentation` を `クイックスタートドキュメンテーション` と翻訳すると、パッと見でリンク先がイメージしづらいような気がしたので、 `クイックスタート文書` と翻訳するようにしたというふうに記憶してます...。
- https://docs.google.com/spreadsheets/d/1FyDI0iaG-v-VsocWrUyDmfabBbb5CD08VNrTTdhgcgQ/edit#gid=1649883626&range=A26:C26

逆に、現在 `ドキュメンテーション` と翻訳されているOSMクイックスタートの方でも、文書化と翻訳してしまうと、見る方に伝わりにくくなるような気もしましたので、無理に統一せず、文脈に応じて使い分けるのが良いように思いました。
- https://osgeo-jp.github.io/OSGeoLive-doc/ja/quickstart/osm_quickstart.html

(個人的には、 `Documentation` をあえて `ドキュメント` と翻訳するのも、分かりやすい文章にするという意味では、ありかと思ってます...。)

**Comment by miurahr** [comment]
このゆれは、問題ないということで、クローズします。
