### ISSUE TITLE
[日本語訳文] ソフトウエアとソフトウェアのゆれ

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#32]
**問題の説明**
software,  software versionの翻訳について、ソフトウエアとソフトウェアのゆれがある。

**修正案についての説明**
Google検索では、 ソフトウェア 180,000.000件  ソフトウエア 60、000、000件

ブリタニカ事典、デジタル大辞泉では、 ソフトウエア を採用
https://kotobank.jp/word/%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A8%E3%82%A2-90310

wikipediaでは、 ソフトウェア を採用

関連： #29

**Comment by miurahr** [comment]
どちらかを用語集に登録して、品質チェックをおこなうことで、修正できるとおもわれる。

**Comment by sanak** [comment]
Google検索結果件数 (ソフトウェアがソフトウエアの3倍)、Wikipedia (https://ja.wikipedia.org/wiki/%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2) ともに、ソフトウェアが良いように思いました。

用語集の方でも、現状、 `Software Version` を `ソフトウェアバージョン` として登録してますので、ソフトウェアに合わせる形が良いと思います。
https://github.com/OSGeo-jp/OSGeoLive-doc-omegat/blob/master/glossary/glossary.txt#L28

**Comment by miurahr** [comment]
done
