### ISSUE TITLE
[日本語訳文] shapefileの訳文にゆれ

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#33]
**問題の説明**
shapefileは表記のゆれがある

16 | shape   | シェイプ   
--  | ---------- | -- 
15 | shapefile | シェープファイル ,シェイプファイル
4 | shapefiles | シェープファイル , シェイプファイル
2 | Shapefiles | シェープファイル   
1 | external shapefiles | シェープファイル   
1 | new multi-sided shape | 新しい多辺形状   
1 | output shapefile | 出力シェイプファイル 
1 | shape file | シェイプファイル 

**修正案についての説明**
シェイプファイル に統一

関連： #29

**Comment by sanak** [comment]
Shapefileの訳語ですが、Wiki、Shapefile仕様を策定したEsriの日本総販売代理店(Esriジャパン)の仕様、ともに、 `シェープファイル` として訳してますので、フォーマットとして翻訳する場合は、そのまま、 `シェープファイル` と翻訳する形が良いと思います。

- [シェープファイル - Wikipedia](https://ja.wikipedia.org/wiki/%E3%82%B7%E3%82%A7%E3%83%BC%E3%83%97%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB)
- [シェープファイルについて | ESRIジャパン](https://www.esrij.com/getting-started/learn-more/shapefile/)

対して、形状の意味で翻訳する場合は、分かりやすいように `形状` として翻訳した方が良いと思います。

**Comment by miurahr** [comment]
ideeditor_quickstartでのつぎの訳出は、形状でしょうか。

> 4096>  Drawing shapes (polygons)
>             形状(ポリゴン)を描画する
> 4097>  To add a new multi-sided shape, click on the **Area** button.
>             新しい多辺形状を追加するには、 **領域** ボタンをクリックします。
> 4101> You will notice that the color of your shape will change depending on the attributes that you assign to it.
>             形状色は、割り当てるアトリビュートに応じて変化します。
> 4103> The tools that are available when you select a shape and activate the context menu with the right mouse button are similar to those when you click on a line.
> 形状を選択して右マウスボタンでコンテキストメニューを表示したときに使用できるツールは、ラインをクリックしたときのツールと似ています。

**Comment by miurahr** [comment]
josm_quickstartは、 learnOSMのJOSMの章、ほぼ そのものです。
https://learnosm.org/ja/josm/start-josm/

こちらでは、シェイプと訳出しており、josm_quickstartでも、他の部分をふくめて、おなじ訳を採用しています。
ここでのシェイプは、ポリゴンの意味で使用されています。

**Comment by sanak** [comment]
@miurahr  
> ideeditor_quickstartでのつぎの訳出は、形状でしょうか。
> :

はい、ideditor_quickstart での訳出は形状で問題ないと思います。
(別件で、 `Area` の訳出は、iDエディタのボタン名に合わせて、 `領域` でなく、 `エリア` の方が良いと思いました。)
https://osgeo-jp.github.io/OSGeoLive-doc/ja/quickstart/ideditor_quickstart.html

> josm_quickstartは、 learnOSMのJOSMの章、ほぼ そのものです。
> https://learnosm.org/ja/josm/start-josm/

> こちらでは、シェイプと訳出しており、josm_quickstartでも、他の部分をふくめて、おなじ訳を採用しています。
> ここでのシェイプは、ポリゴンの意味で使用されています。

上記、了解しました。シェイプの訳出のままで問題ないと思います。

OSGeoLiveはアプリが複数混じっていますが、アプリ内での文言については、各アプリでの訳語優先で良いと思います。

**Comment by sanak** [comment]
下記PRで修正を確認しましたので、こちらはクローズします。
https://github.com/OSGeo-jp/OSGeoLive-doc/pull/10

(以下については、私の方でチェックついでに修正しておきます。)
> はい、ideditor_quickstart での訳出は形状で問題ないと思います。
> (別件で、 Area の訳出は、iDエディタのボタン名に合わせて、 領域 でなく、 エリア の方が良いと思いました。)
