### ISSUE TITLE
[新規翻訳] leaflet_quickstart.po

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#47]
![image](https://user-images.githubusercontent.com/123720/107139607-caca5780-695f-11eb-9889-a9bd8923477f.png)

**Comment by miurahr** [comment]
訳了

**Comment by miurahr** [comment]
![image](https://user-images.githubusercontent.com/123720/107902136-e3062c00-6f88-11eb-9d0f-7b4d0d2740a7.png)

**Comment by sanak** [comment]
こちら、Transifex pushがまだでしたが、いくつか気になった点があったので、勝手ながら以下の修正を行いました。
- https://github.com/OSGeo-jp/OSGeoLive-doc-omegat/commit/bb185ae881f06f48c1b99f0c534bf63cded7e940
- https://github.com/OSGeo-jp/OSGeoLive-doc-omegat/commit/da64b57fb413369690e974e9c2cd58c23bdc0e47
- https://github.com/OSGeo-jp/OSGeoLive-doc-omegat/commit/16ea9f2fac7a574a059634477c9ae3dd050cf41f
- https://github.com/OSGeo-jp/OSGeoLive-doc-omegat/commit/751a05fa6d8540beece5d238e766674b63b80af5

**Comment by miurahr** [comment]
bb185ae　について、ever の訳出が消えました。代案はどうなりますか？

**Comment by sanak** [comment]
@miurahr  
ご指摘ありがとうございます。  
`yet .. ever ...` の不足分を埋める意味だけで考えると、下記になるような気もしていましたが、
- 変更前: 軽量ですが、ほとんどの開発者がオンライン地図に必要とするすべての機能を備えています。
- 変更後: 軽量ですが、 **かつて** ほとんどの開発者がオンライン地図に必要と~~する~~ **していた** すべての機能を備えています。

社内で海外出身メンバーに確認したところ、 `It is lightweight, yet has all the features most developers ever need for online maps.` の文脈だと、
- `yet` は `however` (もしくは `nonetheless`)
- `ever` は `never ~ anymore`

ということでしたので、 `yet`/`ever` の訳出を含めるとなると、
- 変更後: 軽量ですが、ほとんどの開発者がそれ以上を必要としない、すべての機能を備えています

のような形になると思います。

ただ、原文に `ever` があるのが適切でないのではという意見もありましたので、無理に `yet`/`ever` を訳さず、現行のままでも良いような気がしました。

**Comment by miurahr** [comment]
了解です。原文も改善の余地ありってことですね。

**Comment by sanak** [comment]
> 原文も改善の余地ありってことですね。

はい...。  
確認ありがとうございます。 :bow:
