### ISSUE TITLE
copyrightの免責条項に誤訳の可能性

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#5]
> 免責事項
OSGeoLiveのコンテンツは、著作権保持者および貢献者によって」現状のまま」提供され、商品性および特定目的への適合性の黙示的な保証を含む(ただし、これらに限定されない)、明示的または暗示的ないかなる保証も拒否されます。いかなる場合においても、著作権所有者または貢献者は、直接的、間接的、付随的、特別、懲罰的、または結果的な損害(代替の商品またはサービスの調達、使用、日付、または利益の損失、またはビジネスの中断を含むが、これらに限定されない)に対して責任を負わないものとします。ただし、契約、厳格な賠償責任、または不法行為(過失またはその他を含む)のいずれによるものであるかを問わず、いかなる責任の理論に基づくものであっても、かかる損害の可能性について事前に知らされていたとしても、このソフトウェアの使用によって*発生したとします。*

>  arising in any way out of the use of this software, 
> このソフトウェアの使用によって*発生したとします。*

out of the use of this software このソフトウエアの使用以外で
in any way いずれにせよ、
arising 生じる

本分節のS+Vは、"(In no event) shall the copyright owner or contributors be liable " であるので、「発生したとします。」という動詞にならない可能性がたかい。

**Comment by miurahr** [comment]
@smellman 11月1日に当該を翻訳されていますが、意見をおねがいします。

**Comment by miurahr** [comment]
既存の訳でも同じ問題があったようです。

**Comment by miurahr** [comment]
ただし、契約、厳格な賠償責任、または不法行為(過失またはその他を含む)のいずれによるものであるかを問わず、いかなる責任の理論に基づくものであっても、損害の可能性について警告されたとしてさえ、かかる損害はこのソフトウエアの利用による発生ではありません。

**Comment by sanak** [comment]
@miurahr (CC: @smellman)  
誤訳については、適宜修正して頂いても問題ないかもしれません。
(もしくは、Google Spreadsheetの各行の備考欄セルでコメントを入れてメンションをするのが良い気がしてきました...。)

また、メモは、Transifexのコメントでなく、OmegaTの方の機能でしょうか？
私のローカル環境のOmegaTチームプロジェクトで該当文節を選択してもメモ欄に表示がなかったので、関連ファイルのコミットが必要になるかもしれません。

また、個人的にはTextraの翻訳結果のままの方が良いように思いました。
> :
> ただし、契約、厳格な賠償責任、または不法行為(過失またはその他を含む)のいずれであるかを問わず、いかなる責任の理論に基づいて、本ソフトウェアの使用によって発生したいかなる損害についても、たとえそのような損害の可能性について知らされていたとしても、責任を負わないものとします。*
> \<TexTra Powered by NICT\>

**Comment by miurahr** [comment]
最終的に、@sanak の案にしました。

**Comment by sanak** [comment]
こちら、対応ありがとうございました。
クローズします。
