### ISSUE TITLE
[新規翻訳] grass_quickstart.po

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#50]
![image](https://user-images.githubusercontent.com/123720/107139701-9b681a80-6960-11eb-8ca3-f8c26f44e81b.png)

**Comment by sanak** [comment]
@miurahr  
GrassのQuickstartは、OSGeoLive 11時点で確か @nuimura さんに翻訳頂いていたものを、まだ移行できてない状態だったと思いますので、私の方で、下記の旧(Transifex移行前の)翻訳を参考に、埋めていくようにします。
- [GRASS GIS 7 クィックスタート — OSGeo-Live 11.0 Documentation](http://adhoc.osgeo.osuosl.org/livedvd/docs/ja/quickstart/grass_quickstart.html)

メンション頂き、ありがとうございます！ 🙇‍♂️

**Comment by miurahr** [comment]
![image](https://user-images.githubusercontent.com/123720/107902203-1f398c80-6f89-11eb-908c-9ab4e61e5683.png)

**Comment by sanak** [comment]
2/20(土)は用事があるため、2/21(日)に翻訳予定です。

**Comment by sanak** [comment]
`Adjust raster map colors` 章は、原文の辻褄が合わないため、作者に確認が取れるまで未訳とします...。
- https://trac.osgeo.org/osgeolive/ticket/2291#comment:5

なお、GRASS起動後の2画面以降は一部翻訳されている形になりますが、ラスタ・ベクタ・レイヤの表記が異なっていたため、これらの訳文はアプリ画面側に合わせます。(#58 に関連)
![grass_translation_difference](https://user-images.githubusercontent.com/629923/109378430-d9c87800-7915-11eb-8f22-ab5b9558ebd2.png)

**Comment by sanak** [comment]
週末中、ほぼ進みませんでしたが、3/3の翻訳デッドラインまでには進めるようにします...。

**Comment by sanak** [comment]
3D表示部分が少し残ってますが、今晩には下記の不要箇所を除いて仕上げるようにします...。

> Adjust raster map colors 章は、原文の辻褄が合わないため、作者に確認が取れるまで未訳とします...。
> 
> https://trac.osgeo.org/osgeolive/ticket/2291#comment:5

**Comment by miurahr** [comment]
現在、全体でも 87% の進捗となりました。

**Comment by sanak** [comment]
> 現在、全体でも 87% の進捗となりました。

上記、了解です。いつもありがとうございます。 :bow:

**Comment by sanak** [comment]
Adjust raster map colors 章を除いて翻訳・Transifex/GitHub Push済みです。
クローズします。
