### ISSUE TITLE
[英語原文] Rasdaman quickstartにリンク不適切

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#51]
**問題の説明**
rasdaman quickstart のリンク先について、認証をもとめられるため、チュートリアルとしては不適切。

> Explore the `rasdaman documentation <https://doc.rasdaman.org>`_ to learn about rasdaman administration, its query language, and data ingestion.

https://doc.rasdaman.org  が不適切

**Comment by sanak** [comment]
@miurahr  
上記ですが、私の環境(macOS Catalina, Chrome)からだと認証プロセスなく、ログイン可能でした。  
ご利用のブラウザは、Linux上のFirefoxになりますか？

また、別件で、訳語の先頭に半角の空白スペースがあると、Sphinxビルド時に認識されずに英語原文のままとなるようです。  
最後の2文が英語原文のままと認識されてましたので、念のため、報告します。
- [Rasdaman クイックスタート — OSGeoLive 14.0 Documentation](https://osgeo-jp.github.io/OSGeoLive-doc/ja/quickstart/rasdaman_quickstart.html)

**Comment by miurahr** [comment]
あれ、いまはみえました。一時的なものだったようです。

**Comment by sanak** [comment]
上記リンクの件、了解です。

下記で少し修正を加えましたので、念のため報告します。
- https://github.com/OSGeo-jp/OSGeoLive-doc-omegat/commit/7db1620c245a71abca181ce3a33f19070ea8e5a9
