### ISSUE TITLE
[新規翻訳] mapslicer_quickstart.po

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#52]

**Comment by miurahr** [comment]
訳了

**Comment by miurahr** [comment]
wait Transifex upload
![image](https://user-images.githubusercontent.com/123720/108448381-f248ea80-72a4-11eb-9ac9-a7f2a56f3c63.png)

**Comment by sanak** [comment]
MapSlicerですが、最新では下記の一覧からたどれず、リンクも無くなっているようでした。
- https://osgeo-jp.github.io/OSGeoLive-doc/ja/overview/overview.html

Transifexには、まだリソースが存在するため、取り急ぎ、翻訳頂いた状態のものを、Transifex pushのみしておきます。

**Comment by sanak** [comment]
1箇所、 `ArcGIS` が `ArgGIS` と訳されてましたので、そこだけ修正後、Transifex pushしておきます。
- https://github.com/OSGeo-jp/OSGeoLive-doc-omegat/commit/9237cd5efb7fe40a717a493b4b37e015ce2b3530

**Comment by sanak** [comment]
こちら、一旦クローズします。
