### ISSUE TITLE
[新規翻訳] mapproxy_quickstart.po

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#53]

**Comment by miurahr** [comment]
訳了

**Comment by miurahr** [comment]
wait an upload to transifex

![image](https://user-images.githubusercontent.com/123720/108448104-78186600-72a4-11eb-8190-e63e045fa938.png)

**Comment by sanak** [comment]
下記でざっとですが、内容を確認しました。  
https://osgeo-jp.github.io/OSGeoLive-doc/ja/quickstart/mapproxy_quickstart.html

1箇所だけ、末尾が `〜だ。` となっている箇所があったため、そこだけ、他と同様に `〜です。` に変更しました。
- https://github.com/OSGeo-jp/OSGeoLive-doc-omegat/commit/bba07ec7167fb4bc851a2f2e0d2b4c80e4abf7dd

Transifexにpush済みのため、クローズします。
