### ISSUE TITLE
[新規翻訳] actinia_quickstart.po

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#54]
![image](https://user-images.githubusercontent.com/123720/107903148-c91a1880-6f8b-11eb-9530-415c7c600bb3.png)

**Comment by miurahr** [comment]
![image](https://user-images.githubusercontent.com/123720/108447846-f6c0d380-72a3-11eb-901f-2a9255e6bb7c.png)

**Comment by sanak** [comment]
下記でざっとですが、内容を確認しました。
https://osgeo-jp.github.io/OSGeoLive-doc/ja/quickstart/actinia_quickstart.html

`ツール( details )` の箇所のみ、 `ツール(詳細)` と表示されるよう、少し修正しました。
- https://github.com/OSGeo-jp/OSGeoLive-doc-omegat/commit/0e072bad10a0df8c3d2bd65cbf67b3f4cfb7005c

Transifexにpush済みのため、クローズします。
