### ISSUE TITLE
[日本語訳文] Defaultの訳語統一

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#58]
**問題の説明**
デフォルト 既定 のゆれがある
#29 

**修正案についての説明**
デフォルトに統一

**Comment by sanak** [comment]
@miurahr  
上記、ありがとうございます。  
デフォルト以外にも、ユーザー => ユーザ、レイヤー => レイヤ など、全般にカタカナ訳語末尾の長音は使用しない件、了解しました。

取り急ぎ、該当PR(https://github.com/OSGeo-jp/OSGeoLive-doc/pull/27) で変更のあったpoファイル中、訳語統一のみのものについて、Transifexへのpushが完了しましたので、該当PRについて、一旦マージします。(訳語統一以外も含むものについては、別途、今晩中を目処にレビューの上、マージします。)

**Comment by sanak** [comment]
1箇所、geonetwork_quickstartにて、既定 => 初期 に変更された訳がありましたので、下記にて、デフォルトに訳し直しておきました。
- https://github.com/OSGeo-jp/OSGeoLive-doc-omegat/commit/c4af6cb081eaa857e4b6cfbba322fd8456743d5e

**Comment by miurahr** [comment]
ここは、意味をとって敢えて初期設定としました。デフォルト設定に戻す　では、日本語として不明確になるためです。

**Comment by sanak** [comment]
@miurahr  
上記、了解です。

私の方だと、初期 = Initial のようなイメージなので、原文の方を修正した方が良いような気がしてきました...。

取り急ぎ、後ほど(明日中目処で)、初期設定に戻すようにします。

**Comment by miurahr** [comment]
ああ、なるほど。だとすると、デフォルト設定　とする意味があります。デフォルト設定でいきましょう。

**Comment by sanak** [comment]
上記、了解です。  
確認ありがとうございます。 :bow:
