### ISSUE TITLE
[バグ] インデックスページの目次が英語になってしまう(翻訳されない)

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#60]
**バグの説明**
ヘルプのトップページの目次が翻訳されていない。

**原因**
この原因は、Sphinxのバグとおもわれる。
https://github.com/sphinx-doc/sphinx/issues/4683

この問題は、Sphinx v2.3.0以降で修正されている。OSGEo-Liveのプロセッシングについて、バージョンが古い可能性あり。
https://github.com/sphinx-doc/sphinx/commit/fcdeafd56e67cc38dcd56862cc0ee6304178a3e8

**イメージ**

![image](https://user-images.githubusercontent.com/123720/108582013-f42daf00-7373-11eb-919a-c8fc8744238c.png)

**当該文書のソース**

https://github.com/OSGeo/OSGeoLive-doc/blob/master/doc/index.rst

```

Quick Starts
--------------------------------------------------------------------------------

.. toctree::
  :maxdepth: 1

  quickstart/osgeolive_quickstart
  quickstart/internationalisation_quickstart
  quickstart/osgeolive_install_quickstart
  quickstart/virtualization_quickstart
  quickstart/usb_quickstart
  quickstart/hyperv_quickstart
  quickstart/commandline_quickstart

.. toctree::
  :hidden:

  overview/overview

.. toctree::
  :maxdepth: 1
  :hidden:
  :glob:

  contact
  copyright
  download
  sponsors
  sponsors_osgeo
  metrics
  osgeo_contact


```

**Comment by miurahr** [comment]
Sphinxのバージョンがふるすぎる

```
sphinx==1.6.5
sphinx-intl==0.9.10
```

https://github.com/OSGeo/OSGeoLive-doc/blob/master/requirements.txt

**Comment by sanak** [comment]
@miurahr  
こちらの件、私の方からVickyに直接伝えてしまい、こちらにIssueの作成ができてなくて申し訳ないです...。

Vickyの方で下記で対応したということだったのですが、念のため、私の方でもSphinxビルドして確認してみます。
- https://trac.osgeo.org/osgeolive/ticket/2315
- https://github.com/OSGeo/OSGeoLive-doc/pull/691

**Comment by sanak** [comment]
取り急ぎ、上記のPRがマージされたようだったので、手元のローカル環境でupstreamのmasterブランチをSphinxビルドして確認しましたが、日本語翻訳にはなっているようでした。

![updadted_index_po](https://user-images.githubusercontent.com/629923/108613590-d5dcb780-7436-11eb-950d-ea0f2035df23.png)

ただ、タイトル訳がそのまま表示されていて、少し冗長な気もしましたので、各クイックスタートのタイトル部分の原文側の調整か、訳文側での調整(意訳)が必要かもしれません。

参考までに、以前キャプチャした、Transifex移行前のOSGeoLive 11.0のイメージを貼っておきます。  
https://trac.osgeo.org/osgeolive/attachment/ticket/2315/osgeolive-ja_toppage.jpg  
![osgeolive-ja_toppage](https://user-images.githubusercontent.com/629923/108613628-189e8f80-7437-11eb-847a-b28511fdc8a9.png)

**Comment by sanak** [comment]
英語原文側のデッドラインが今日(2/24)までということに先ほど気付きましたので、
https://lists.osgeo.org/pipermail/osgeolive/2021-February/015225.html

取り急ぎ、以下のOSGeoLiveのTracにコメントを追加しました。
https://trac.osgeo.org/osgeolive/ticket/2315#comment:3

**Comment by miurahr** [comment]
修正されました
