### ISSUE TITLE
[日本語訳文] EOxクイックスタートの修正・同期

### ISSUE THREAD

**Issue by sanak** [OSGeo-jp/OSGeoLive-doc-omegat#61]
**問題の説明**
下記のEOxServerクイックスタートについて、タイトル部分のタイポ(`クイックスタートt`)や原文更新に伴う未訳箇所が見受けられました。
- 作業用Webサイト: https://osgeo-jp.github.io/OSGeoLive-doc/ja/quickstart/eoxserver_quickstart.html
- 原文更新分コミット: https://github.com/OSGeo/OSGeoLive-doc/commit/ae56ed0836e4ada98de1552ddbec58a3959d8144#diff-aac1f6a11632ff2d2bc602648366deb56c01ad82ddb06297a24b1d9893c71ed5

**修正案についての説明**
タイポの修正と、原文更新に伴う訳文の更新が必要の見込みです。

**Comment by miurahr** [comment]
訳文を更新しました。

![image](https://user-images.githubusercontent.com/123720/109728483-9d3c9b00-7bf9-11eb-99ee-1bef2ee39cfe.png)

**Comment by sanak** [comment]
@miurahr こちら対応ありがとうございました。:bow:  
Transifex Push済みのため、クローズします。
