### ISSUE TITLE
[新規翻訳] quickstart/postgis_quickstart.po

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#63]
原文更新にともないpostgis_quickgisに11の文について未翻訳があります

![image](https://user-images.githubusercontent.com/123720/109603529-45545480-7b65-11eb-8739-b0fa01f1fb42.png)

**Comment by miurahr** [comment]
![image](https://user-images.githubusercontent.com/123720/109603624-674dd700-7b65-11eb-9057-fea16d4a857f.png)

**Comment by sanak** [comment]
@miurahr ありがとうございます。朝方少し訳してたのですが、仕事の方で途中になってました。今晩目処で確認します。

**Comment by miurahr** [comment]
あとはGRASSだけでも完成させましょう。

**Comment by sanak** [comment]
> あとはGRASSだけでも完成させましょう。

了解です。GRASSは明日にかけてとなる気がしますが、3/3のデッドラインまでには完了させるようにします。 😅

**Comment by sanak** [comment]
@miurahr 確認の上、TransifexにPushしました。
対応ありがとうございました。 🙇‍♂️
