### ISSUE TITLE
[新規翻訳] quickstart/gpsprune_quickstart.po

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#66]
![image](https://user-images.githubusercontent.com/123720/109743318-d4b84100-7c13-11eb-893e-2afd232f7803.png)

**Comment by miurahr** [comment]
> To find out how long the climb is, we will select just the part of the track which contains the climb, and then we will be able to view the properties of this selected range, such as the distance, climb and descent.

の訳語として、

>上昇の長さを確認するには、上昇を含むトラックの部分だけを選択し、選択した範囲のプロパティ(距離、上昇、下降など)を表示します。

でよいか

**Comment by miurahr** [comment]
![image](https://user-images.githubusercontent.com/123720/109744866-5c06b400-7c16-11eb-8aa8-6d988731e920.png)

**Comment by sanak** [comment]
@miurahr  
翻訳の対応、ありがとうございます！

> 上昇の長さを確認するには、上昇を含むトラックの部分だけを選択し、選択した範囲のプロパティ(距離、上昇、下降など)を表示します。

下記で日本語訳文を流し読みしましたが、標高プロファイルの画像キャプチャもあるので、上昇・下降でそれほど不自然には感じられませんでした。
https://osgeo-jp.github.io/OSGeoLive-doc/ja/quickstart/gpsprune_quickstart.html

ただ、該当訳文の下の手順5.で `"Range Details" セクションでは、この部分の長さが8.55kmで、346mを登って10mだけ下っていることがわかります` と訳されてましたので、上昇 => 登り、下降 => 下り と訳すのもありな気もしました。

取り急ぎ、一旦現状のままでTransifexにPushしておきますので、後ほど、確認をお願いします。

**Comment by miurahr** [comment]
> ただ、該当訳文の下の手順5.で "Range Details" セクションでは、この部分の長さが8.55kmで、346mを登って10mだけ下っていることがわかります

長さ→距離 または 道程 のほうがよさそうですね。 

この部分の道程が8.55kmで、道中に346m上昇し10m下降したことがわかります

**Comment by sanak** [comment]
@miurahr 了解です。細かい部分の修正("" => 「」の変換漏れ)のPullRequestを、日本語訳の最終Fixとして投げるつもりですが、上記の変更も含めたほうが良さそうであれば、対応します。(UTC時間の3/3として、あと1時間ほどは(多分)大丈夫かと考えてます... 😅 )

**Comment by sanak** [comment]
@miurahr 9:00からミーティングがあることを失念していました...。
取り急ぎ、下記に日本語訳最終版としてPullRequestを作成しましたので、報告します。
- https://github.com/OSGeo/OSGeoLive-doc/pull/700

**Comment by miurahr** [comment]
将来のために論点部分を更新しました。

**Comment by sanak** [comment]
こちら、対応ありがとうございました。
OSGeoLive 15の方でも問題なさそうでしたので、クローズします。
https://osgeo-jp.github.io/OSGeoLive-doc/ja/quickstart/gpsprune_quickstart.html
