### ISSUE TITLE
[新規翻訳] pygeoapi_quickstart.po

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#67]

**Comment by miurahr** [comment]
![image](https://user-images.githubusercontent.com/123720/109747879-45169080-7c1b-11eb-906a-726abe945945.png)

**Comment by sanak** [comment]
@miurahr 確認の上、TransifexにPushしました。
対応ありがとうございました。 🙇‍♂️
