### ISSUE TITLE
[バグ] 新規追加 Jupyter の原文がソースに存在しない

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#69]
**バグの説明**

1月末に、Jupyter_overview , jupyter_quickstart が追加されているが、プロジェクトに存在しない

**Comment by miurahr** [comment]
とりいそぎ、Transifexの更新だけしてあります。

**Comment by sanak** [comment]
@miurahr 上記、了解です。
対応ありがとうございます！ 🙇

**Comment by sanak** [comment]
こちらもOssim同様、大分以前にTransifexの設定ファイルから削除されたままになっていたようです。
- https://github.com/OSGeo/OSGeoLive-doc/commit/c57a38e9d8caf881177a7e62923aefebb8bf35fd#diff-e071df9d84c80d98b07a7efe464ea1b4e92ab493b5c52f5d0f37ca69266ebc3f

**Comment by miurahr** [comment]
おかしいですね。
2021年1月31日にTransifexの原文が更新されていますので、有効なのかとおもいました。

**Comment by miurahr** [comment]
https://github.com/OSGeo/OSGeoLive-doc/commit/d2b6e001c6628d2466cf49f2a94253e0ce14d56c#diff-e071df9d84c80d98b07a7efe464ea1b4e92ab493b5c52f5d0f37ca69266ebc3f

メンテナーによる、上記のメンテナンスのときに、.tx/config に Jupyter関連を追加するのをわすれたようです。

**Comment by miurahr** [comment]
https://github.com/OSGeo/OSGeoLive-doc/pull/701

**Comment by sanak** [comment]
こちらですが、OSGeoLive 15の方でも問題なさそうでしたのでクローズします。
- https://osgeo-jp.github.io/OSGeoLive-doc/ja/overview/jupyter_overview.html
- https://osgeo-jp.github.io/OSGeoLive-doc/ja/quickstart/jupyter_quickstart.html
