### ISSUE TITLE
[バグ] ossimの原文がプロジェクトに存在しない

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc-omegat#70]
**バグの説明**

ossim_overview.po と ossim_quickstatrt.po がsourceにない

**Comment by sanak** [comment]
本家の方での経緯の確認は必要ですが、下記でTransifexからPullするソースから削除されたようでした。
- https://github.com/OSGeo/OSGeoLive-doc/commit/3710a58846c829185324e5366c604fb55efdc128#diff-e071df9d84c80d98b07a7efe464ea1b4e92ab493b5c52f5d0f37ca69266ebc3f

**Comment by miurahr** [comment]
こちらは放棄されたようですので、対処不要でクローズとします。
